# Acknowledgments {#sec-apx-acknowledgments}

For authors and citation details, see @sec-apx-citation.

The authors also thank **Aaron T. L. Lun** for feedback, advice, as well as his substantial contributions to the Bioconductor ecosystem; **Abby Spangler**, **Madhavi Tippani**, and **Brenda Pardo** for initial work and discussions on Visium data analysis workflows and preprocessing procedures carried out at the Lieber Institute for Brain Development; and members of the **Bioconductor Core Team and community** for computational assistance and advice. In addition, the authors thank readers from the Bioconductor and wider research communities for feedback, suggestions, and contributions.

<!--
## Authors and contributors

The following individuals have contributed to developing the contents of this book (in alphabetical order):

🇮🇹 Ilaria Billato, University of Padova, Italy  
🇨🇭 Peiying Cai, University of Zurich, Zurich, Switzerland  
🇺🇸 [Leonardo Collado-Torres](https://lcolladotor.github.io/), Lieber Institute for Brain Development, Baltimore, MD, United States  
🇪🇸 [Helena L. Crowell](https://helenalc.github.io/), National Center for Genomic Analysis, Barcelona, Spain   
🇨🇭 [Estella Yixing Dong](https://estellad.github.io/online-cv/), CHUV and University of Lausanne, Lausanne, Switzerland  
🇨🇭 [Martin Emons](https://github.com/mjemons), University of Zurich, Zurich, Switzerland  
🇦🇺 [Shila Ghazanfar](https://shazanfar.github.io/), University of Sydney, Sydney, Australia  
🇨🇭 [Raphael Gottardo](https://www.chuv.ch/en/bdsc/), CHUV and University of Lausanne, Lausanne, Switzerland  
🇨🇭 [Samuel Gunz](https://github.com/sgunz), University of Zurich, Zurich, Switzerland  
🇺🇸 [Boyi Guo](https://boyi-guo.com/), Johns Hopkins University, Baltimore, MD, United States  
🇺🇸 [Stephanie C. Hicks](https://www.stephaniehicks.com/), Johns Hopkins University, Baltimore, MD, United States  
🇩🇪 [Artür Manukyan](https://artur-man.github.io/), Max Delbrück Center for Molecular Medicine, Berlin, Germany  
🇮🇹 Dario Righelli, University of Naples Federico II, Italy  
🇺🇸 [Keri Martinowich](https://neuroscience.jhu.edu/research/faculty/56), Lieber Institute for Brain Development, Baltimore, MD, United States  
🇺🇸 [Kristen Maynard](https://neuroscience.jhu.edu/research/faculty/166), Lieber Institute for Brain Development, Baltimore, MD, United States  
🇦🇺 Pratibha Panwar, University of Sydney, Sydney, Australia  
🇦🇺 [Ellis Patrick](https://ellispatrick.github.io/), University of Sydney, Australia  
🇦🇺 Shreya Rao, University of Sydney, Australia  
🇮🇹 [Davide Risso](https://drisso.github.io/), University of Padova, Italy  
🇨🇭 [Mark D. Robinson](https://robinsonlabuzh.github.io/), University of Zurich, Zurich, Switzerland  
🇦🇺 Callum Sargeant, Walter and Eliza Hall Institute, Melbourne, Australia  
🇨🇭 Jieran Sun, CHUV and University of Lausanne, Lausanne, Switzerland  
🇺🇸 [Michael Totty](https://github.com/MicTott), Johns Hopkins University, Baltimore, MD, United States  
🇺🇸 [Lukas M. Weber](https://lmweber.org/), Boston University, Boston, MA, United States

## Bioconductor

We are grateful to members of the [Bioconductor Core Team](https://www.bioconductor.org/about/core-team/) for assistance with the creation and maintenance of the book and its infrastructure, specifically (in alphabetical order):

🇺🇸 [Vince Carey](https://vjcitn.github.io/), Harvard Medical School, Boston, MA, United States  
🇺🇸 [Lori Ann (Shepherd) Kern](https://www.bioconductor.org/about/core-team/), Roswell Park Comprehensive Cancer Center, Buffalo, NY, United States  
🇺🇸 [Alexandru Mahmoud](https://www.bioconductor.org/about/core-team/), Harvard Medical School, Boston, MA, United States

We are also grateful to the [Bioconductor](https://bioconductor.org/) community for ongoing feedback, discussion, and additional development assistance.
-->

- This book is built using [**BiocBook**](https://bioconductor.org/packages/release/BiocBook), developed by [Jacques Serizay](https://jserizay.com/) for building Quarto books with Bioconductor. More details on BiocBook can be found in this [demo](https://bioconductor.org/books/release/BiocBookDemo/).

- This book is inspired by the **Orchestrating Single-Cell Analysis with Bioconductor (OSCA)** book [@Amezquita2020-OSCA] on analysis workflows for single-cell data using R and Bioconductor, available [here](https://bioconductor.org/books/release/OSCA/).

- Details on data preprocessing procedures for **10x Genomics Visium** data can be found in our related online book [Visium data preprocessing](https://lmweber.org/Visium-data-preprocessing/).

- **Feedback and suggestions** may be provided as [GitHub](https://github.com/lmweber/OSTA) issues for discussion with the maintainers.

## References {.unnumbered}
