# Visium HD workflow

## Introduction
<!-- TODO --->

## Dependencies

```{r deps, message=FALSE, warning=FALSE}
library(OSTA.data)
library(VisiumIO)
library(SpatialExperiment)
library(ggspavis)
library(spacexr)
library(ggplot2)
library(patchwork)
library(DropletUtils)
library(BiocParallel)
library(scran)
library(scater)
library(pheatmap)
```

In this example of Visium breast cancer data [@Janesick2023], we perform Visium cell type deconvolution without Chromium reference and compare the concordance with the provided Visium annotation by 10x Genomics.

```{r load-vhd8}
# retrieve dataset from OSF repo
id <- "VisiumHD_HumanColon_Oliveira"
pa <- OSTA.data_load(id)
dir.create(td <- tempfile())
unzip(pa, exdir=td)

# read 008um bins into 'SpatialExperiment'
vhd8 <- VisiumIO::TENxVisiumHD(
  spacerangerOut = td,
  images = "lowres",
  processing = "filtered",
  bin_size = "008",
  format = "h5"
) |> VisiumIO::import()
rownames(vhd8) <- make.unique(rowData(vhd8)$Symbol)

# retrieve 008um bin annotations 
# df <- read.csv(file.path(td, "annotation.csv"))
df <- read.csv(gzfile("~/Downloads/DeconvolutionResults_P2CRC.csv.gz"), row.names = 1)
df <- df[complete.cases(df), ]
cx <- intersect(colnames(vhd8), rownames(df))

# keep only VisiumHD 008um with a provided annotation
vhd8 <- vhd8[, cx]

# add as metadata
colData(vhd8)[names(df)] <- df[cx, ]

vhd8
```

```{r load-vhd16}
# read 016um bins into 'SpatialExperiment'
vhd16 <- VisiumIO::TENxVisiumHD(
  spacerangerOut = td,
  images = "lowres",
  processing = "filtered",
  bin_size = "016",
  format = "h5"
) |> VisiumIO::import()
rownames(vhd16) <- make.unique(rowData(vhd16)$Symbol)
vhd16
```
```{r plt-vhd}
plotVisium(vhd8, annotate = "DeconvolutionLabel1",
           zoom = TRUE, point_size = 1, show_axes = TRUE) +
  xlim(c(400, 410)) + ylim(c(250, 260))
```

## Quality control

## Clustering

## Deconvolution


## References {.unnumbered}
