# Workflow: CosMx {#sec-img-workflow-cosmx}

## Premable

### Introduction

### Dependencies

```{r load-libs, message=FALSE, warning=FALSE}
library(osfr)
library(scran)
library(scater)
library(igraph)
library(BiocParallel)
library(SpatialExperiment)
library(SpatialExperimentIO)
bp <- MulticoreParam(10)
```

## Importing

```{r load-data, message=FALSE}
# TODO: tmp fix  (awaiting 'OSTA.data' updates)
# to skip (down)loading polygons & transcripts
url <- "https://osf.io/5n4q3"
no <- osf_retrieve_node(url)
ids <- c(
    "CosMx1k_MouseBrain1",
    "CosMx1k_MouseBrain2")
spe <- lapply(ids, \(id) {
    df <- osf_ls_files(no, pattern=id)
    df <- osf_ls_files(df)
    df <- df[-grep("tx", df$name), ]
    dir.create(td <- tempfile())
    osf_download(df, td)
    spe <- readCosmxSXE(td, addTx=FALSE)
    spe$sample_id <- id
    return(spe)
}) |> do.call(what=cbind)
```

## Quality control

```{r}
spe <- spe[, colSums(counts(spe) > 1) >= 10]
```

```{r}
pat <- "c_[0-9]+_([0-9]+)_([0-9]+)$"
.df <- data.frame(
    fov=as.integer(gsub(pat, "\\1", df$cell_id)),
    cell_ID=as.integer(gsub(pat, "\\2", df$cell_id)),
    Annotation=df$Annotation)

one <- spe[, spe$sample_id == "CosMx1k_MouseBrain1"]
colData(one) <- DataFrame(dplyr::left_join(
    data.frame(colData(one)), 
    .df, by=c("fov", "cell_ID")))

gg <- data.frame(colData(one), spatialCoords(one))
ggplot(gg, aes(col=Annotation,CenterX_global_px, CenterY_global_px)) +
    geom_point(shape=16, size=0.4, stroke=0) +
    theme_void() + coord_equal() +
    theme(legend.position="none")
```

```{r}
df <- read.csv("~/Downloads/MB1_CT.csv")
fd <- read.csv("~/Downloads/MB2_CT.csv")

.df <- data.frame(
    fov=gsub("c_[0-9]+_[0-9]+_([0-9]+)$", "\\1", df$cell_id),
    cell_id=gsub("c_[0-9]+_([0-9]+)_[0-9]+$", "\\1", df$cell_id),
    annotation=df$Annotation)

one <- spe[, spe$sample_id == "CosMx1k_MouseBrain1"]
two <- spe[, spe$sample_id == "CosMx1k_MouseBrain2"]

colnames(one) <- sprintf("c_1_%s_%s", one$fov, one$cell_ID)
colnames(two) <- sprintf("c_2_%s_%s", two$fov, two$cell_ID)

one$k <- df$Annotation[match(colnames(one), df$cell_id)]
two$k <- fd$Annotation[match(colnames(two), fd$cell_id)]

gg <- data.frame(colData(one), spatialCoords(one))
ggplot(gg, aes(col=k,CenterX_global_px, CenterY_global_px)) +
    geom_point(shape=16, size=0.4, stroke=0) +
    theme_void() + coord_equal() +
    theme(legend.position="none")

gg <- data.frame(colData(two), spatialCoords(two))
ggplot(gg, aes(col=k,CenterX_global_px, CenterY_global_px)) +
    geom_point(shape=16, size=0.4, stroke=0) +
    theme_void() + coord_equal() +
    theme(legend.position="none") 
```

## Feature selection

```{r}
spe <- logNormCounts(spe, size.factors=spe$Area.um2)
tbl <- modelGeneVar(spe, block=spe$sample_id)
length(sel <- getTopHVGs(tbl))
```

## Dimension reduction

```{r}
spe <- runPCA(spe, subset_row=sel, BPPARAM=bp)
spe <- runUMAP(spe, dimred="PCA", BPPARAM=bp)
```

## Clustering

```{r}
# build cellular shared nearest-neighbor (SNN) graph
g <- buildSNNGraph(spe, use.dimred="PCA", type="jaccard", k=20)
# cluster using Leiden community detection algorithm
k <- cluster_leiden(g, objective_function="modularity", resolution=0.8)
table(spe$Leiden <- factor(k$membership))
```

```{r}

```

## Downstream analyses

## Appendix

### References {.unnumbered}
