# Cell-cell communication {#sec-img-cell-cell-communication}

## Preamble

### Introduction

Cell-cell communication analyses aim to investigate how cells interact within tissues through signaling pathways and communication networks.

Several methods have been developed for these types of analyses. In general, these methods require annotated cell types, spatial coordinates, and curated lists of ligand-receptor (L-R) pairs (and optionaly pathway or target gene sets) as inputs. Ligand-receptor pairs can be accessed from databases including `OmniPath`, `CellChatDB`, `CellPhoneDB`, and others.


### Example

Here, we demonstrate a short example using `COMMOT` [@Cang2023-COMMOT], an optimal transport-based approach that models competition between sender and receiver signals, considers physical distances, and easily links to public databases.

Since `COMMOT` is available as a Python package, we can access it from R using `r BiocStyle::Biocpkg("reticulate")` and `r BiocStyle::Biocpkg("basilisk")` (see @sec-bkg-python-interoperability).


```{r eval=FALSE}
# dependencies
suppressPackageStartupMessages({
    library(scater)
    library(reticulate)
    library(BiocParallel)
    library(zellkonverter)
    library(SingleCellExperiment)
    library(basilisk)
    library(OSTA.data)
    library(SpatialExperimentIO)
})

# setup
bp <- MulticoreParam(4)

env <- BasiliskEnvironment(
  envname = "img-ccc", 
  pkgname = "base", 
  packages = c("python=3.11"), 
  pip = c("commot==0.0.3")
)

use_virtualenv(obtainEnvironmentPath(env))


#env_path <- obtainEnvironmentPath(env)
#py <- file.path(env_path, "bin", "python")
#libdir <- file.path(env_path, "lib")

#Sys.setenv(
#  DYLD_LIBRARY_PATH          = libdir,
#  DYLD_FALLBACK_LIBRARY_PATH = libdir,
#  RETICULATE_PYTHON          = py
#)

#use_python(py, required = TRUE)
#py_config()


# loading
# retrieve dataset from OSF repository
#id <- "CosMx6k_HumanBrain"
#pa <- OSTA.data_load(id)
#dir.create(td <- tempfile())
#unzip(pa, exdir=td)
#(spe <- readCosmxSXE(td, addTx=FALSE))


sce <- readRDS(...)
sce <- logNormCounts(sce, BPPARAM=bp)

# wrangling
xy <- spatialCoords(sce)
reducedDim(sce, "spatial") <- xy

# run 'COMMOT'
ad <- import("anndata")
pd <- import("pandas")
ct <- import("commot")

# retrieve LR interaction from CellChatDB & filter for 
# those that are fully covered by the 1k-plex CosMx panel
db <- ct$pp$ligand_receptor_database(database="CellChat", species="human")
names(db) <- c("ligand", "receptor", "pathway", "type"); nrow(db)
db <- db[apply(db, 1, \(.) {
    rs <- strsplit(.["receptor"], "_")
    lr <- c(.["ligand"], unlist(rs))
    all(lr %in% rownames(sce))
}), ]; nrow(db)

# subset to features being considered
rs <- sapply(strsplit(db$receptor, "_"), .subset, 1)
nrow(sce <- sce[unique(c(db$ligand, rs)), ])

is <- split(colnames(sce), sce$fov)
sr <- bplapply(is, BPPARAM=bp, \(.) { 
    # skip FoV when there are too few cells
    if (length(.) < 100) return(NULL) 
    ad <- SCE2AnnData(sce[, .], X_name="logcounts")
    ct$tl$spatial_communication(ad,
        database_name="CellChatDB",
        # average cell is 10x10um; here, we consider 
        # a distance threshold of 10 cells = 0.1mm
        dis_thr=0.1,  
        df_ligrec=db,
        heteromeric=TRUE,
        pathway_sum=TRUE,
        heteromeric_rule="min",
        heteromeric_delimiter="_")
    list(
        ad$obsm["commot-CellChatDB-sum-sender"], 
        ad$obsm["commot-CellChatDB-sum-receiver"])
})
```


## Appendix

### References {.unnumbered}
